version: "3.8"
services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
        
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "5000:5000"

  frontend:
    container_name: frontend
    build: ./frontend/planzo
    ports:
      - "3000:3000"     

